import type { Metadata } from "next";
import "./globals.css";
import RecoilRootProvider from "@/utils/RecoilRootComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-[100%]">
        <RecoilRootProvider>{children}</RecoilRootProvider>
        <div className="hidden bg-custom_ice bg-custom_skyBlue bg-custom_lightBlue bg-custom_blue bg-custom_navy bg-custom_yellow bg-custom_peach bg-custom_orange bg-custom_lightGrey bg-custom_cloud bg-custom_skyGrey bg-custom_smog bg-custom_mint "></div>
        <div id="portal"></div>
      </body>
    </html>
  );
}
